# This file may be used to create a conda environment using:
#  conda env create --prefix=${HOME}/miniconda3/envs/lvn3p14 --file environment.yml
name: lvn3p14
channels:
  - conda-forge
dependencies:
  - python=3.14
  - meson
  - pybind11
  - ninja
  - twine
  - numpy
  - jupyter
  - ipython
  - matplotlib  
  - pandas
  - tqdm
  - ffmpeg-python  # optional: for video generation of grid image time series