#
# Configuration file for meson-python wrapper around Meson build system.
#


[build-system]
build-backend = "mesonpy"
requires = ["meson-python", "wheel", "pybind11", "ninja", "numpy"]

[project]
name = 'lvn'
version = '2025.10.31a2'
# dynamic = ["version"]
description = 'Integration of Langevin equations representing absorbing phase transitions'
readme = 'README.md'

requires-python = '>=3.12'
dependencies = [
    "pybind11",
    "numpy",
    "jupyter",
    "ipython",
    "matplotlib",
    "pandas",
    "tqdm",
    "ffmpeg-python"
]

authors = [
  {name = 'Colin P. Stark', email = 'cstarkjp@gmail.com'},
]
keywords = [
  'Langevin equation', 
  'directed percolation', 
  'operator splitting',
  'stochastic differential equations',
  'phase transition'
]
# Development Status :: 2 - Pre-Alpha 
# Development Status :: 3 - Alpha
# Development Status :: 4 - Beta
# Development Status :: 5 - Production/Stable
classifiers = [
  "Development Status :: 3 - Alpha",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Topic :: Scientific/Engineering :: Physics",
  "Intended Audience :: Science/Research",
  "Programming Language :: C++",
  "Programming Language :: Python :: 3",
  "Operating System :: MacOS",
  "Operating System :: POSIX :: Linux",
  "Operating System :: Microsoft :: Windows"
]

[project.urls]
homepage = "https://cstarkjp.github.io/Langevin"
repository = "https://github.com/cstarkjp/Langevin"
documentation = "https://cstarkjp.github.io/Langevin"
# "Bug Tracker" = "https://github.com/cstarkjp/Langevin"


